function USRPTransmit(InterpolationFactor, txOrg,numOfPackets)
% Setup transmitter
hSDRu = comm.SDRuTransmitter( ...
    'Platform' , 'N200/N210/USRP2', ... 'Platform', 'B200', ...
    'IPAddress','192.168.0.4', ...'SerialNum', '30A3E93', ... 
    'CenterFrequency',      2.3e9, ...
    'InterpolationFactor',  InterpolationFactor,...
    'Gain',                 30,...    
    'MasterClockRate',      100e6);

% hSDRu = comm.SDRuTransmitter( ...
%     'Platform', 'B200', ...
%     'SerialNum', '30A3E93', ...
%     'CenterFrequency',      2.2e9, ...
%     'InterpolationFactor',  1,...
%     'Gain',                 10,...
%     'MasterClockRate',      20e6);
    
    

% Run transmitter
disp('Transmitting... pew! pew!');
for framesTransmitted = 1:numOfPackets
    % Send data to USRP
    step(hSDRu, txOrg);    
end

release(hSDRu);